### ISSUE TITLE
请教公式中的字母含义

### ISSUE THREAD

**Issue by U-uU** [ls1rius/WSI_FiVE#1]
你好，关于在公式10中提到的交叉熵损失函数，请问里面的soft targets(在公式中标为y_ij)和i、j该怎样理解呢

**Comment by ls1rius** [comment]
表示一个batch中的第i张图片与第j个病理报告描述

**Comment by ls1rius** [comment]
> 你好，关于在公式10中提到的交叉熵损失函数，请问里面的soft targets(在公式中标为y_ij)和i、j该怎样理解呢
表示一个batch中的第i张图片与第j个病理报告描述

**Comment by ls1rius** [comment]
> 你好，关于在公式10中提到的交叉熵损失函数，请问里面的soft targets(在公式中标为y_ij)和i、j该怎样理解呢

表示一个batch中的第i张图片与第j个病理报告描述

**Comment by U-uU** [comment]
> > 你好，关于在公式10中提到的交叉熵损失函数，请问里面的soft targets(在公式中标为y_ij)和i、j该怎样理解呢
> 
> 表示一个batch中的第i张图片与第j个病理报告描述

请问y_ij是图片标签还是什么呢？

**Comment by ls1rius** [comment]
> > > 你好，关于在公式10中提到的交叉熵损失函数，请问里面的soft targets(在公式中标为y_ij)和i、j该怎样理解呢
> > 
> > 
> > 表示一个batch中的第i张图片与第j个病理报告描述
> 
> 请问y_ij是图片标签还是什么呢？

单张wsi对应唯一的病例报告。
p_ij近似于表示每张wsi和每份病理报告之间的特征相似度。
y_ij是真值，表示当前wsi是否对应当前病例报告，大部分情况下是0或者1，当然你也可以做一些smooth。
