### ISSUE TITLE
About LUAD_report.csv and LUSC_report.csv

### ISSUE THREAD

**Issue by future97** [ls1rius/WSI_FiVE#10]
Are there any specific preprocessing steps applied to the reports in LUAD_report.csv and LUSC_report.csv that make them slightly different from the corresponding samples in TCGA_Reports.csv? Could you please share the relevant preprocessing workflow?

Looking forward to your response, and thank you very much in advance.

**Comment by ls1rius** [comment]
No specific preprocessing steps were taken. 
The data from https://github.com/tatonetti-lab/tcga-path-reports were simply divided into LUAD_report.csv and LUSC_report.csv according to their type.

**Comment by future97** [comment]
Using the example of TCGA-05-4244.3a844132-f813-4d8e-8f7d-dbae0b23d7fd, in the **TCGA_Reports.csv**, the diagnosis is as follows: "1. Resection material from the right lower lobe of the lung with a peripheral, non-mucigenous, papillary adenocarcinoma, 4.5 cm in size, with foci of poor differentiation, with pleural infiltration and invasion of the blood vessels, hilar lymph node metastases. Tumor classification: M-8140/3, G. 3, pT 2, pV 0, pN 2, pMx, stage III A. R0."

However, in the **LUAD_report.csv**, the diagnosis is stated as: "The patient has a 4.5 cm non-mucinous, papillary adenocarcinoma located in the right lower lobe of the lung. The tumor exhibits areas of poor differentiation, pleural infiltration, and vascular invasion, with metastases present in the hilar lymph nodes. The tumor is classified as M-8140/3, G3, pT2, pV0, pN2, pMx, indicating a stage IIIA disease. The resection margins are clear (R0)."

Is the difference here related to any preprocessing procedures?

**Comment by ls1rius** [comment]
I apologize for forgetting to explain a step here. Just tell gpt "you are a doctor, and summarize it", and you can get this preprocessed text.
This is an experimental approach used in previous research. And subsequent experiments did use this text.
Actually, I initially attempted to align the entire summarized text but found the results unsatisfactory and decided to abandon that approach. 
However, you can proceed with the original TCGA_Reports.csv for subsequent GPT-based information extraction without significantly affecting the experimental outcomes.

**Comment by future97** [comment]
OK, thank you for your patient response.
