### ISSUE TITLE
Questions about the few shot experiment setup

### ISSUE THREAD

**Issue by du-67** [ls1rius/WSI_FiVE#12]
Hi，author.  I would like to ask how to change the training samples to conduct different few-shot experiments? I didn't see any related parameter settings in the code. 
Looking forward to your response, and thank you very much in advance.

**Comment by ls1rius** [comment]
You can randomly select a small number of samples from the existing training set. For instance, an 8-shot experiment involves sampling 8 WSI image-report pairs. 
Simply modify the annotations of the training set accordingly is enough.

**Comment by du-67** [comment]
Thank you for your patient reply!
Are you saying that the code provides experiments using all training data, and before conducting  few shot experiments requires randomly extracting the required training data  in advance? Do I still need to modify the CSV file provided by the project? 
looking forward to your reply，thank you!

**Comment by ls1rius** [comment]
yes

**Comment by du-67** [comment]
OK！Thank you so much.
