### ISSUE TITLE
No such file or directory:

### ISSUE THREAD

**Issue by arivexu** [ls1rius/WSI_FiVE#14]
您好，请问您在/dataset/pipeline.py中的第1704行
`img_pth = osp.join(data_prefix, filename).replace('LUAD-patch', 'LUADSC-patch-embed-pub').replace(
                'LUSC-patch', 'LUADSC-patch-embed-pub').replace('/patch/', '/patch-embed-pub/') + '.csv'`
中生成的csv文件路径，该csv文件是怎么获得的呢，我运行后的生成结果为
`data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-50-5045-01Z-00-DX1.csv `
期待您的回复

**Comment by ls1rius** [comment]
这个是采用的预训练参数的patch进行的实验。
你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。

**Comment by arivexu** [comment]
> 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。

好的，已经解决这个问题了，谢谢。

**Comment by Kiritooo** [comment]
> 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。

您好，感谢您对工作的分享

我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢

**Comment by Kiritooo** [comment]
> 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。

您好，感谢您对工作的分享

我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢

**Comment by ls1rius** [comment]
> > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> 
> 您好，感谢您对工作的分享
> 
> 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢

你看下路径对不对，以及该文件是否存在。

**Comment by Kiritooo** [comment]
> > > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> > 
> > 
> > 您好，感谢您对工作的分享
> > 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢
> 
> 你看下路径对不对，以及该文件是否存在。

我和lz一样 data目录下是

data
--TCGA-lung-patch_report
--/LUAD_LUSC_data_desc_reid.csv
--/LUAD_LUSC_data_desc_reid_delval.csv
--/LUAD_LUSC_data_train_reid.csv
--/LUAD_LUSC_data_val_reid.csv
--/LUAD_LUSC_labels_desc_reid.csv
--/LUAD_LUSC_labels_reid.csv
--/LUAD_LUSC_labels_train_reid.csv
--/LUAD_LUSC_labels_val_reid.csv

datasets下是
datasets
--tcga-dataset
--/tcga_lung_data_feats
--/LUAD.csv
--/LUSC.csv
--/TCGA.csv
 
没有 /TCGA-lung-patch_report/LUADSC-patch-embed-pub/ 这个路径 请问是哪里理解错了吗  感谢！

**Comment by Kiritooo** [comment]
> > > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> > 
> > 
> > 您好，感谢您对工作的分享
> > 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢
> 
> 你看下路径对不对，以及该文件是否存在。

我和lz一样 data目录下是

data
|--TCGA-lung-patch_report
|--|--LUAD_LUSC_data_desc_reid.csv
|--|--LUAD_LUSC_data_desc_reid_delval.csv
|--|--LUAD_LUSC_data_train_reid.csv
|--|--LUAD_LUSC_data_val_reid.csv
|--|--LUAD_LUSC_labels_desc_reid.csv
|--|--LUAD_LUSC_labels_reid.csv
|--|--LUAD_LUSC_labels_train_reid.csv
|--|--LUAD_LUSC_labels_val_reid.csv

datasets下是

datasets
|--tcga-dataset
|--|--tcga_lung_data_feats
|--|--LUAD.csv
|--|--LUSC.csv
|--|--TCGA.csv
 
没有 /TCGA-lung-patch_report/LUADSC-patch-embed-pub/ 这个路径 请问是哪里理解错了吗  感谢！

**Comment by ls1rius** [comment]
> > > > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> > > 
> > > 
> > > 您好，感谢您对工作的分享
> > > 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢
> > 
> > 
> > 你看下路径对不对，以及该文件是否存在。
> 
> 我和lz一样 data目录下是
> 
> data |--TCGA-lung-patch_report |--|--LUAD_LUSC_data_desc_reid.csv |--|--LUAD_LUSC_data_desc_reid_delval.csv |--|--LUAD_LUSC_data_train_reid.csv |--|--LUAD_LUSC_data_val_reid.csv |--|--LUAD_LUSC_labels_desc_reid.csv |--|--LUAD_LUSC_labels_reid.csv |--|--LUAD_LUSC_labels_train_reid.csv |--|--LUAD_LUSC_labels_val_reid.csv
> 
> datasets下是
> 
> datasets |--tcga-dataset |--|--tcga_lung_data_feats |--|--LUAD.csv |--|--LUSC.csv |--|--TCGA.csv
> 
> 没有 /TCGA-lung-patch_report/LUADSC-patch-embed-pub/ 这个路径 请问是哪里理解错了吗 感谢！

需要自己编辑一下，可以尝试修改代码中的路径读取方式。
于dataset/pipeline.py中的第1704行

也可以修改csv文件中的数据存储路径来适配你的存储路径

**Comment by Kiritooo** [comment]
> > > > > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> > > > 
> > > > 
> > > > 您好，感谢您对工作的分享
> > > > 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢
> > > 
> > > 
> > > 你看下路径对不对，以及该文件是否存在。
> > 
> > 
> > 我和lz一样 data目录下是
> > data |--TCGA-lung-patch_report |--|--LUAD_LUSC_data_desc_reid.csv |--|--LUAD_LUSC_data_desc_reid_delval.csv |--|--LUAD_LUSC_data_train_reid.csv |--|--LUAD_LUSC_data_val_reid.csv |--|--LUAD_LUSC_labels_desc_reid.csv |--|--LUAD_LUSC_labels_reid.csv |--|--LUAD_LUSC_labels_train_reid.csv |--|--LUAD_LUSC_labels_val_reid.csv
> > datasets下是
> > datasets |--tcga-dataset |--|--tcga_lung_data_feats |--|--LUAD.csv |--|--LUSC.csv |--|--TCGA.csv
> > 没有 /TCGA-lung-patch_report/LUADSC-patch-embed-pub/ 这个路径 请问是哪里理解错了吗 感谢！
> 
> 需要自己编辑一下，可以尝试修改代码中的路径读取方式。 于dataset/pipeline.py中的第1704行
> 
> 也可以修改csv文件中的数据存储路径来适配你的存储路径

好的 是根据论文中的几种设定 选|--|--tcga_lung_data_feats 中不同的csv进行训练对吗

**Comment by ls1rius** [comment]
> > > > > > 这个是采用的预训练参数的patch进行的实验。 你可以按照本项目的REAME中的Data Preparation -> Pathology Image Dataset中介绍的对该数据进行下载。
> > > > > 
> > > > > 
> > > > > 您好，感谢您对工作的分享
> > > > > 我对于WSI这块也是刚开始了解，想请问下：下载了您提供的 precomputed features https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip 并按地址解压后直接运行pth的train还是会报错[Errno 2] No such file or directory: /data/TCGA-lung-patch_report/LUADSC-patch-embed-pub/TCGA-77-8128-01Z-00-DX1.csv 是缺少了哪些步骤呢
> > > > 
> > > > 
> > > > 你看下路径对不对，以及该文件是否存在。
> > > 
> > > 
> > > 我和lz一样 data目录下是
> > > data |--TCGA-lung-patch_report |--|--LUAD_LUSC_data_desc_reid.csv |--|--LUAD_LUSC_data_desc_reid_delval.csv |--|--LUAD_LUSC_data_train_reid.csv |--|--LUAD_LUSC_data_val_reid.csv |--|--LUAD_LUSC_labels_desc_reid.csv |--|--LUAD_LUSC_labels_reid.csv |--|--LUAD_LUSC_labels_train_reid.csv |--|--LUAD_LUSC_labels_val_reid.csv
> > > datasets下是
> > > datasets |--tcga-dataset |--|--tcga_lung_data_feats |--|--LUAD.csv |--|--LUSC.csv |--|--TCGA.csv
> > > 没有 /TCGA-lung-patch_report/LUADSC-patch-embed-pub/ 这个路径 请问是哪里理解错了吗 感谢！
> > 
> > 
> > 需要自己编辑一下，可以尝试修改代码中的路径读取方式。 于dataset/pipeline.py中的第1704行
> > 也可以修改csv文件中的数据存储路径来适配你的存储路径
> 
> 好的 是根据论文中的几种设定 选|--|--tcga_lung_data_feats 中不同的csv进行训练对吗

是的
