### ISSUE TITLE
few-shot实验中随机种子

### ISSUE THREAD

**Issue by du-67** [ls1rius/WSI_FiVE#15]
您好！请问在少样本实验中有关于seed的设置吗，应该设置为多少？还是直接随机选取的样本呢？
另外，我注意到您在论文的选用TOP等模型作为对比实验，这些实验都是利用DSMIL数据集进行的吗？评估标准都是最高准确率ACC吗？
非常期待您的回复！

**Comment by ls1rius** [comment]
随机选取的样本，多次实验后取得平均值，因此seed影响不大

对比实验大部分都是以DSMIL数据集进行的实验。
我们提供了两套方案，一种是end2end，一种是DSMIL预训练参数，总体上二者性能差别不大。subtype的zero-shot实验上采用end2end性能会更好。

评估标准我们取得是平均准确率ACC

**Comment by du-67** [comment]
感谢您的回复！请问LUAD_LUSC_labels_train_reid.csv文件里面的内容是什么呢？是对每一张图像都生成的相应的病理报告吗？

**Comment by ls1rius** [comment]
是的 每一组slice一个报告
