### ISSUE TITLE
对比实验

### ISSUE THREAD

**Issue by arivexu** [ls1rius/WSI_FiVE#16]
您好，

我注意到您在对比实验中使用了TOP框架，想请教一下，您在实验中使用的TOP结果是自己复现的吗？如果是的话，能否请您分享一下train_patch_feat.h5、train_patch_corresponding_slide_label.npy、train_patch_corresponding_slide_index.npy、train_patch_corresponding_slide_name.npy、train_patch_label.npy文件是如何获得的？

非常抱歉打扰您，因我在复现该框架时使用了自己提取的npy文件，结果出现了过拟合现象，所以希望能向您请教一些经验。

感谢您的时间与帮助！

**Comment by ls1rius** [comment]
不好意思，我们也没有复现TOP结果，直接用的原文的结论。
具体复现建议你可以直接问问TOP的作者
