### ISSUE TITLE
About pretrain data

### ISSUE THREAD

**Issue by qfchou** [ls1rius/WSI_FiVE#3]
Hi,

Thank you for sharing your excellent work.

In fully supervised experiments, the paper said that "Note that the test data is not used in pre-training. " The test data is TCGA Lung data, so what is the pretrain data? I don't find any detailed information about how to pretrain the model for supervised learning.

Thank you in advance and looking forward your answers!

**Comment by ls1rius** [comment]
The overall method is the pre-training method, and the fully supervised experiment is the downstream task verification after pre-training.  Additionally, to further assess the effectiveness of the pre-training, we conducted few-shot experiments in 4.4.

**Comment by qfchou** [comment]
So the pre-train data is also TCGA Lung Cancer. "Note that the test data is not used in pre-training." in 4.5 means that you use train and valid data for pre-train first, and use these two split data for training a surpervised model and get results on test data. 

Is this right?

**Comment by ls1rius** [comment]
Actually, we only use train data for pre-train first.

**Comment by qfchou** [comment]
Got it! Thank you so much.
