### ISSUE TITLE
Preprocess the original PDF file

### ISSUE THREAD

**Issue by winston52** [ls1rius/WSI_FiVE#8]
Hi,

Thank you for your excellent work!

 When I tried to apply your method to another type of cancer in the TCGA dataset, I encountered a problem while preprocessing the original PDF file. I used the LLM model to extract raw text from the TCGA report automatically. However, the LLM predicts the text in the black masking area, which is inconsistent with the original report. I wonder if you can share the code for preprocessing the PDF file? Thank you.

**Comment by ls1rius** [comment]
We downloaded the ready-made text directly from https://github.com/tatonetti-lab/tcga-path-reports.
We are sorry we do not have the code to process PDF files. 
You may consult the original author for the PDF processing code.

**Comment by winston52** [comment]
Thank you for your clarification.
