### ISSUE TITLE
关于训练所用的数据集

### ISSUE THREAD

**Issue by MengXinAAA** [ls1rius/WSI_FiVE#9]
您好，

1.在您提供的TCGA图像特征中，每张20倍率的WSI图片的patch数量几乎都不到一万个，甚至大多数五千个以内，而我使用dsmil的代码切出来的20倍率的patch数量普遍都在上万个，请问您在切图片的时候是有什么特殊处理吗？

2.您提供的图片特征就是通过您提供的代码端到端训练中得出的吗？还是说用其他的代码训练提取的特征，如果是的话方便提供一下代码吗，非常感谢！

谢谢

**Comment by ls1rius** [comment]
我提供的图片特征就是dsmil提供的数据，据他们的回复是进行了simclr预训练。
这批数据应该是大小为512x512切的，dsmil的代码本身默认切片大小好像是256x256。切片代码你用dsmil的就可以。
我的代码提供了两套训练方案，一套是可以自己切patch然后端到端训练的，另一套则是用预训练的特征（这批特征就是dsmil提供的）。
